name: Comfirm Message

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  print-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: confirm.py ${{ github.event.issue.url }} ${{ secrets.GITHUB_TOKEN }}
